spring:
  data:
    mongodb:
      host: localhost
      database: library
      port: 27017
mongock:
  change-logs-scan-package:
    - ru.otus.ovodkov.homework11.changelogs
  runner-type: initializingbean
